name:                auth-dsl
version:             0.1.0.0
github:              "auth-dsl/auth-dsl"
license:             BSD3
author:              "Auth DSL Team"
maintainer:          "team@auth-dsl.com"
copyright:           "2025 Auth DSL Team"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Domain-specific language for authentication systems
category:            Web

description:         Please see the README on GitHub at <https://github.com/auth-dsl/auth-dsl#readme>

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- time
- containers
- megaparsec
- servant
- servant-server
- warp
- postgresql-simple
- sqlite-simple
- bcrypt
- jwt
- http-client
- http-client-tls
- http-conduit
- wai
- wai-cors
- wai-extra
- optparse-applicative
- bytestring
- mtl
- transformers
- stm
- async
- uuid
- random
- scientific
- cookie
- cryptonite
- base64-bytestring
- http-types
- resource-pool
- regex-tdfa
- hashable
- case-insensitive
- warp-tls
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  auth-dsl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - auth-dsl

tests:
  auth-dsl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - auth-dsl
    - hspec
    - hspec-wai
    - hspec-wai-json
    - QuickCheck
    - temporary